/* Logger */
const {hatsuLogger} = require('../../Support/Logger');

module.exports = {
    events: "warn",
    once: false,
    run(info) {
        hatsuLogger.warnLog("Hatsu", `This is Just a Warning Generated by Hatsu!, You can safely ignore this warning\n ${info}`);
    }
}